services:
- postgresql

before_script:
- psql -c 'create database taco_api_test;' -U postgres

env:
- DB:postgresql

script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/

language: ruby
rvm:
- 2.3.1